/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/animals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Animals
         * @description Get all animals with optional filters
         *
         *     - **animal_class**: Filter by class (e.g., "Mammal", "Bird")
         *     - **habitat**: Filter by habitat keyword
         *     - **species**: Filter by species name
         */
        get: operations["list_animals_api_animals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animals/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search animals by name, species, or interesting facts
         *
         *     - **q**: Search query string
         */
        get: operations["search_api_animals_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animals/{animal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Animal
         * @description Get a single animal by ID
         *
         *     - **animal_id**: Unique animal identifier
         */
        get: operations["get_animal_api_animals__animal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Statistics
         * @description Get statistics about the animal collection
         *
         *     Returns counts by:
         *     - Animal class
         *     - Diet type
         *     - Habitat
         *     - Conservation status
         */
        get: operations["get_statistics_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API information
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Animal
         * @description Complete animal data model
         */
        Animal: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Species */
            species: string;
            animal_class: components["schemas"]["AnimalClass"];
            /** Habitat */
            habitat: string;
            diet: components["schemas"]["Diet"];
            /**
             * Lifespan
             * @description Average lifespan in the wild
             */
            lifespan: string;
            /**
             * Behavior
             * @description Typical behavioral characteristics
             */
            behavior: string;
            /**
             * Size
             * @description Typical size/length
             */
            size: string;
            /**
             * Weight
             * @description Typical weight
             */
            weight: string;
            /**
             * Speed
             * @description Maximum speed if applicable
             */
            speed?: string | null;
            /**
             * Color
             * @description Primary coloration
             */
            color: string;
            /** Interesting Fact */
            interesting_fact: string;
            conservation_status: components["schemas"]["ConservationStatus"];
        };
        /**
         * AnimalClass
         * @description Classification of animals by their biological class
         * @enum {string}
         */
        AnimalClass: "Mammal" | "Bird" | "Reptile" | "Amphibian" | "Fish" | "Invertebrate";
        /**
         * AnimalStats
         * @description Statistics about the animal collection
         */
        AnimalStats: {
            /** Total Animals */
            total_animals: number;
            /** By Class */
            by_class: {
                [key: string]: number;
            };
            /** By Diet */
            by_diet: {
                [key: string]: number;
            };
            /** By Habitat */
            by_habitat: {
                [key: string]: number;
            };
            /** By Conservation Status */
            by_conservation_status: {
                [key: string]: number;
            };
        };
        /**
         * ConservationStatus
         * @description IUCN Conservation Status
         * @enum {string}
         */
        ConservationStatus: "Least Concern" | "Vulnerable" | "Endangered" | "Critically Endangered";
        /**
         * Diet
         * @description Dietary classification
         * @enum {string}
         */
        Diet: "Carnivore" | "Herbivore" | "Omnivore";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_animals_api_animals_get: {
        parameters: {
            query?: {
                /** @description Filter by animal class */
                animal_class?: string | null;
                /** @description Filter by habitat keyword */
                habitat?: string | null;
                /** @description Filter by species */
                species?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_animals_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_animal_api_animals__animal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statistics_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalStats"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
